### ISSUE TITLE
Node v4.0 and Beyond

### ISSUE THREAD

**Issue by tab58** [scijs/ndarray-blas-level1#12]
I was wondering why Travis doesn't run checks on Node.js beyond v0.12. The primary push for wanting more advanced versions that was more my use of the `Math.sign` function, which was AFAIK introduced in ES2015. I had to polyfill it in for Travis to run correctly.

I'm not sure this is a real issue since the rest of the code is obviously compatible with practically all versions of Node, but I thought I'd bring it up.

**Comment by jaspervdg** [comment]
Are you sure it doesn't? You can set the node versions to test against in the `.travis.yml` file. I previously altered travisify to include at least one later version (0.12, while before that 0.10 was the latest version). Still, you might want to allow for _some_ backwards compatibility (but you might want to make sure that the polyfill is not used when it is not needed).

**Comment by rreusser** [comment]
Good question. Whatever the full answer, the short answer it's out of date and needs a fresh look. I'll add this to the guidelines repo and we can discuss the best approach there.

I think the math.io approach has been to polyfill some built-in functions so that behavior of this stuff is rigorously and consistently guaranteed, but that's a lot of work! See: https://github.com/math-io/signum/blob/master/lib/index.js

**Comment by tab58** [comment]
> I was wondering why Travis doesn't run checks on Node.js beyond v0.12.

I wasn't being clear. Should probably proofread my messages from now on :-) . Anyway, I meant that the current `travis.yml` file here doesn't initiate a check for Node 4 and above.

I understand the reason for backwards compatibility because, after all, these are math libraries and math doesn't really change. I added the polyfill for `Math.sign` to my PR, but I was bringing this up in order to start a discussion about if that's the right thing.

**Comment by jaspervdg** [comment]
Okay, makes sense. Given that we should probably also keep web browsers in mind (which perhaps tend to be a bit more outdated than node, and apparently even IE 11 doesn't support Math.sign!), I think we might want to be somewhat conservative. So the polyfill is probably indeed a good idea (note that for many of these things there are packages that you can use), but the .travis.yml is hopelessly out of date, so feel free to fix that, either manually or through fixing travisify (in the latter case you might want to start from my version of travisify).

**Comment by rreusser** [comment]
Hmm… sounds great, but I'm unable to use travisify: `'Must specify two-factor authentication OTP code.'`. See: https://github.com/substack/travisify/issues/13. Any thoughts? In lieu of that, I'm in the progress of writing up contributing guidelines. I'll include a template `.travis.yml` and will ask for feedback before publishing.

**Comment by rreusser** [comment]
Semi-answer: I've done some cleanup on this repo. `.travis.yml` now looks like [this](https://github.com/scijs/ndarray-blas-level1/blob/cleanup/.travis.yml)

``` yaml
language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
```

Older than 0.10 had some issues it didn't seem like were worth fixing (but correct me if i'm mistaken about that. is it reasonable to assume that people would be using this in really old server code? at any rate, I think the code itself was fine and that it was the dev dependencies that failed).

In PR #13, I've left the `Math.sign` polyfill in place, at least until we standardize on a convention for either polyfilling or pulling in external npm modules.

**Comment by tab58** [comment]
Sounds good. I've opened another issue (Issue #14) for the discussion on polyfills.
