### ISSUE TITLE
Prevent overflow in nrm2

### ISSUE THREAD

**Issue by rreusser** [scijs/ndarray-blas-level1#5]
Nrm2 is a meaningful function for lots of algorithms, but it's not great since the naive implementation square roots the valid floating point range. A floating point aware version normalizes by the max entry, normalizes by the length of the input, and perhaps even orders additions by magnitude of the elements, although that last one seems like too much. This makes it a two step process. Find the magnitude of the input, then add with normalization and rescale the output. Maybe there should be a safe version with optional scale that otherwise falls back to checking the size if not provided. Not the end of the world, but I'd like to keep the algorithms optimized and robust. Perhaps this is best handled by avoiding nrm2 in the first place, when possible. Netlib notes that this function was not added for the sake of optimization.

See: http://www.netlib.org/atlas/developer/atlas_contrib/node60.html

**Comment by tab58** [comment]
I've created a PR to address this: https://github.com/scijs/ndarray-blas-level1/pull/17
