### ISSUE TITLE
Split into files

### ISSUE THREAD

**Issue by rreusser** [scijs/ndarray-blas-level1#9]
Doing these correctly (handling generic matrices, simplifications, type-checking, etc.) requires enough work that this should probably be split into individual repos.

**Comment by tab58** [comment]
Do we really want to divide up the functions into separate repos? For some things, that may make sense, but for a repo implementing BLAS Level 1 I would imagine it would be better to keep the BLAS Level 1 functions together in a single repo. IMO, it's more about doing the least surprising thing to the consumers of this library. 

I would support dividing them into separate files within the repo though.

**Comment by rreusser** [comment]
Yeah, the intermediate solution is [scijs/window-functions](https://github.com/scijs/window-functions) where you can write something like `var blackmanHarris = require('scijs-window-functions/blackman-harris')` so that your project really only actually includes a single file of the larger library.

Philosophically speaking, I like individual repos, but as a matter of practicality, the maintenance becomes a pretty big headache.

**Comment by rreusser** [comment]
Update: splitting this into files is maybe better for maintenance and discoverability.

**Comment by tab58** [comment]
I think we can close this issue, right?
